name: 'olist_semantic'
version: '1.0.0'
config-version: 2
profile: 'olist'

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  olist_semantic:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
